version: "3.8"

services:
  furnistyle-frontend:
    image: burhan503/furnistyle-frontend:v1
    container_name: furnistyle-frontend
    restart: always
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
